name: Run scrapers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # every day at 6am
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4 playwright playwright-stealth
      - run: playwright install chromium
      - run: python scrapers/telmore_scraper.py
      - run: python scrapers/oister_scraper.py
      - run: python scrapers/elgiganten_scraper.py
      - run: python scrapers/cbb_scraper.py
      - run: python scrapers/3_scraper.py
      - run: python scrapers/yousee_scraper.py
      - run: python scrapers/norlys_scraper.py
      - run: python scrapers/pricerunner_scraper.py
#     - run: python scrapers/prisjagt_scraper.py  # disabled for now because it gets blocked by cloudflare
      - uses: actions/checkout@v3  # commit updated JSON files back to repo

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/ public/images/
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
      
